# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0651611f77bf297f4ae408e7a32891b24e6f3c3dc9886d9cc626837dc47530c872cebebdd2b4cdd184139f4c0ec35924f203cfdd9fc1e9930a0f737fcb0ce2b1

test:
  secret_key_base: 4aee6366c6b805f9407d873fcb578e2b7de6027c7e7a4b089088ec3be146a0e86ec7350ce9a39b189a13f68de2bce6ce528a860d27097fdbe4976afec09add6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
